### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by lucasgonze** [statgen/terraform-imputation-server-modules#1]
This repo does not declare its licensing terms. As a result the code must be treated as all rights reserved, but I doubt that is the intention.

**Comment by jdpleiness** [comment]
@lucasgonze I have added a license that is in line with our other software.

I should also mention that this repository is no longer actively developed or used in our production services. While the code should still work with minimal changes, we have no plans to push updates or fixes in the future.

The current code used in production is not public at this time. However, it will likely be released soon after some cleanup and polishing.

**Comment by lucasgonze** [comment]
Thanks for the update. Both the license and notice of inactive status are helpful.
